### ISSUE TITLE
failure to build with gcc 13.2.1 or llvm 17.0.4

### ISSUE THREAD

**Issue by alinelena** [scanberg/viamd#33]
trying to build with gcc 13.2.1 or llvm 17.0.4 results in in enkit not compiling and failing with this error.

```
[ 53%] Building CXX object ext/enkiTS/CMakeFiles/enkiTS.dir/src/TaskScheduler.cpp.o
In file included from /home/drFaustroll/lavello/viamd/ext/enkiTS/src/TaskScheduler.cpp:19:
/home/drFaustroll/lavello/viamd/ext/enkiTS/src/TaskScheduler.h:114:103: error: no template named 'initializer_list' in namespace 'std'
  114 |         template<typename D, typename T>           void SetDependenciesArr( D& dependencyArray_, std::initializer_list<T*> taskpList_ );
      |                                                                                                  ~~~~~^
/home/drFaustroll/lavello/viamd/ext/enkiTS/src/TaskScheduler.h:116:110: error: no template named 'initializer_list' in namespace 'std'
  116 |         template<typename D, typename T, int SIZE> void SetDependenciesArr( D(&dependencyArray_)[SIZE], std::initializer_list<T*> taskpList_ );
      |                                                                                                         ~~~~~^
/home/drFaustroll/lavello/viamd/ext/enkiTS/src/TaskScheduler.h:118:101: error: no template named 'initializer_list' in namespace 'std'
  118 |         template<typename D, typename T>           void SetDependenciesVec( D& dependencyVec_, std::initializer_list<T*> taskpList_ );
      |                                                                                                ~~~~~^
/home/drFaustroll/lavello/viamd/ext/enkiTS/src/TaskScheduler.h:532:70: error: no template named 'initializer_list' in namespace 'std'
  532 |     void ICompletable::SetDependenciesArr( D& dependencyArray_, std::initializer_list<T*> taskpList_ ) {
      |                                                                 ~~~~~^
/home/drFaustroll/lavello/viamd/ext/enkiTS/src/TaskScheduler.h:548:24: warning: variable templates are a C++14 extension [-Wc++14-extensions]
  548 |     void ICompletable::SetDependenciesArr( D(&dependencyArray_)[SIZE], std::initializer_list<T*> taskpList_ ) {
      |                        ^
/home/drFaustroll/lavello/viamd/ext/enkiTS/src/TaskScheduler.h:548:24: error: variable has incomplete type 'void'
/home/drFaustroll/lavello/viamd/ext/enkiTS/src/TaskScheduler.h:548:47: error: use of undeclared identifier 'dependencyArray_'
  548 |     void ICompletable::SetDependenciesArr( D(&dependencyArray_)[SIZE], std::initializer_list<T*> taskpList_ ) {
      |                                               ^
/home/drFaustroll/lavello/viamd/ext/enkiTS/src/TaskScheduler.h:548:77: error: no member named 'initializer_list' in namespace 'std'
  548 |     void ICompletable::SetDependenciesArr( D(&dependencyArray_)[SIZE], std::initializer_list<T*> taskpList_ ) {
      |                                                                        ~~~~~^
/home/drFaustroll/lavello/viamd/ext/enkiTS/src/TaskScheduler.h:548:94: error: 'T' does not refer to a value
  548 |     void ICompletable::SetDependenciesArr( D(&dependencyArray_)[SIZE], std::initializer_list<T*> taskpList_ ) {
      |                                                                                              ^
/home/drFaustroll/lavello/viamd/ext/enkiTS/src/TaskScheduler.h:547:35: note: declared here
  547 |     template<typename D, typename T, int SIZE>
      |                                   ^
/home/drFaustroll/lavello/viamd/ext/enkiTS/src/TaskScheduler.h:548:96: error: expected expression
  548 |     void ICompletable::SetDependenciesArr( D(&dependencyArray_)[SIZE], std::initializer_list<T*> taskpList_ ) {
      |                                                                                                ^
/home/drFaustroll/lavello/viamd/ext/enkiTS/src/TaskScheduler.h:548:98: error: use of undeclared identifier 'taskpList_'
  548 |     void ICompletable::SetDependenciesArr( D(&dependencyArray_)[SIZE], std::initializer_list<T*> taskpList_ ) {
      |                                                                                                  ^
/home/drFaustroll/lavello/viamd/ext/enkiTS/src/TaskScheduler.h:548:110: error: expected ';' at end of declaration
  548 |     void ICompletable::SetDependenciesArr( D(&dependencyArray_)[SIZE], std::initializer_list<T*> taskpList_ ) {
      |                                                                                                              ^
      |                                                                                                              ;
/home/drFaustroll/lavello/viamd/ext/enkiTS/src/TaskScheduler.h:548:111: error: expected unqualified-id
  548 |     void ICompletable::SetDependenciesArr( D(&dependencyArray_)[SIZE], std::initializer_list<T*> taskpList_ ) {
      |                                                                                                               ^
/home/drFaustroll/lavello/viamd/ext/enkiTS/src/TaskScheduler.h:566:68: error: no template named 'initializer_list' in namespace 'std'
  566 |     void ICompletable::SetDependenciesVec( D& dependencyVec_, std::initializer_list<T*> taskpList_ ) {
      |                                                               ~~~~~^
1 warning and 13 errors generated.
gmake[2]: *** [ext/enkiTS/CMakeFiles/enkiTS.dir/build.make:76: ext/enkiTS/CMakeFiles/enkiTS.dir/src/TaskScheduler.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:583: ext/enkiTS/CMakeFiles/enkiTS.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2
```

**Comment by scanberg** [comment]
Thank you for taking the time to compile VIAMD, I will look into this. It is perhaps solved in a later version of enkiTS.

**Comment by scanberg** [comment]
Thanks for the info,
I have updated the enkiTS version that is used.
I suspect that this is a C++20 specific issue. And that std::initializer_list was deprecated or even removed?
It seems that enkiTS has removed its internal usage of std::initializer_list in the current version atleast.

I'm unable to test if this is an actual fix as I don't have those bleeding edge versions of GCC and Clang available on my current machine.

So please let me know if it solves the issue. :)
